### ISSUE TITLE
Cannot install python-client on MACOSX El Captain

### ISSUE THREAD

**Issue by Blizarre** [genestack/python-client#168]
System: Mac OSX El Captain, migrating the python client from 0.8 to 0.9

Problem: the build part of the PyOpenSSL Python package fail, with the c++ compiler failing to find openssl headers. 

Diagnostic:  OpenSSL headers are no longer provided with MacOSX el captain.

Solution: 
- Install openssl using [HomeBrew](http://brew.sh/) : `brew install openssl`
- Build pyopenssl using brew’s openssl headers and libraries:

``` bash
env CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1 LDFLAGS="$(brew --prefix openssl)/lib/libssl.a $(brew --prefix openssl)/lib/libcrypto.a" CFLAGS="-I$(brew --prefix openssl)/include" pip install pyopenssl
```

For more details: https://cryptography.io/en/latest/installation/

**Comment by klas-genestack** [comment]
I've just updated pyOpenSSL to 0.16 without any header quirks.

[Maybe upgrading pip](https://cryptography.io/en/latest/faq/#compiling-cryptography-on-os-x-produces-a-fatal-error-openssl-aes-h-file-not-found-error) would fix the issue more easily?

**Comment by klas-genestack** [comment]
So, what should we do with this issue?

**Comment by Blizarre** [comment]
I think that everybody has fixed the problem now, one way or another. We should close this.

Connor (the trainee) managed to install the python-client directly, without doing any of this voodoo stuff.
