### ISSUE TITLE
genestack_client is not on PyPI

### ISSUE THREAD

**Issue by serverhorror** [genestack/python-client#268]
It is currently pretty cumbersome to use genestack_client in any Python package.

I have this `setup.py` and it fails horribly. How would I have to specify genestack_client to reference a specific version so that it will be `pip`-installable?

```
from setuptools import setup


setup(name='example',
      version='1.0.0',
      description='...',
      author='the-author',
      author_email='alice@example.com',
      url='https://www.example.com',
      python_requires='>=2.7, <=3',
      packages=['example'],
      install_requires=[
          'boto3',
          'genestack_client ~= 0.23',
      ],
      entry_points={
          'console_scripts': [
              'example=example:main',
          ],
      },
      classifiers=[
        'Development Status :: 3 - Alpha',
        'Environment :: Console',
        'Topic :: Utilities',
        ],
      )
```

**Comment by genestack-solomatin** [comment]
You can use dependency_links.  
```
install_requires=[
            "genestack-client"
      ],
      dependency_links=['https://github.com/genestack/python-client/tarball/stable#egg=genestack-client-1.0']
```

```
> pip install . --process-dependency-links
...
Successfully installed example-1.0.0 genestack-client-0.22.0
```

**Comment by serverhorror** [comment]
Will the client be pushed to PyPI?

**Comment by genestack-solomatin** [comment]
> Will the client be pushed to PyPI?

Yes

**Comment by serverhorror** [comment]
Sorry to bother you. Will this one make it into the next release? I heard one is due soon-ish :)

**Comment by alexander-polovtcev** [comment]
Hi! Unfortunately it won't make it there during the current release (which is today), but it will be published until June 5th. Is that convenient for you?

**Comment by klas-genestack** [comment]
Hello, @serverhorror, Genestack Python Client 0.25.0 has been published to PyPI: https://pypi.org/project/genestack-client/
